version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: docker_demo_db
    ports:
      - "3307:3306"  # Change the host port to 3307
    networks:
      - app-network

  app:
    build: .
    container_name: springboot_app
    ports:
      - "8088:8088"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/docker_demo_db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    networks:
      - app-network

networks:
  app-network:
    driver: bridge